services:
  - name: chat-app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_OInDoeA9RTp2@ep-hidden-poetry-a1tlicyt-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
